### ISSUE TITLE
Error line 21

### ISSUE THREAD

**Issue by M4r1uszBuu** [jesus-figueroa/lol-account-checker#16]
![image](https://user-images.githubusercontent.com/86171770/160474229-7c32b50f-63a8-4437-bf6e-b405414ac4ed.png)
Have same error after deleted # too

**Comment by jesus-figueroa** [comment]
Updated, try now.

**Comment by M4r1uszBuu** [comment]
> Updated, try now.

Thank you, I forgot to write that I fixed it. It was enough to leave Accounts = and Timeout =
